import pyray as ray
import glm
from glm import vec2, vec3, ivec2, normalize, cross, dot, atan2, sin, cos, length, radians, degrees

#--RESOLUTION--
WIN_RES = WIN_WIDTH, WIN_HEIGHT = 1920, 1080

MAP_OFFSET = 50
MAP_WIDTH, MAP_HEIGHT = WIN_WIDTH - MAP_OFFSET, WIN_HEIGHT - MAP_OFFSET

EPS = 1e-4

#--PERFORMANCE SETTINGS--
TARGET_FPS = 144

#--CAMERA POSITION--
CAM_HEIGHT = 0.6
CAM_SPEED = 6.2
#--CAMERA ROTATION--
CAM_ROT_SPEED = 3
CAM_DIAG_MOVE_CORR = 1 / pow(2, 0.5)
CAM_PITCH_LIMIT = 90 #Limits the pitch to avoid gimbal lock
CAM_SENSITIVITY = 2.5 
#--CURSOR POSITION--
CENTER_X = WIN_WIDTH // 2
CENTER_Y = WIN_HEIGHT // 2

#--JUMP SETTINGS--
JUMP_VELOCITY = 5.0
GRAVITY = -9.81
JUMP_START_POS = 0.6
JUMP_DURATION = 5.0

#--FIELD OF VIEW--
FOV_Y_DEG = 75

LIGHT_POS = vec2(-30)
#
VEC3_ZERO = ray.Vector3(0,0,0)
VEC2_ZERO = ray.Vector2(0,0)
#
WHITE_COLOR = ray.Color(255, 255, 255, 255)
BLACK_COLOR = ray.Color(0, 0, 0, 255)
DARK_GRAY_COLOR = ray.Color(80, 80, 80, 255)
#
SHADING_COLOR = ray.Color(220, 220, 220, 255)
SHADING_DARK_COLOR = ray.Color(45, 45, 45, 255)